load("@rules_cc//cc:defs.bzl", "cc_binary")

cc_binary(
    name = "hello-world",
    srcs = ["hello-world.cc"],
    deps = ["@amazon-kinesis-video-streams-webrtc-sdk-c//:amazon-kinesis-video-streams-webrtc-sdk-c"],
)
